name: 🐞 Bug
description: Registrar um Bug/Problema
title: "[BUG] <Título>"
labels: [Bug]
body:
- type: checkboxes
  attributes:
    label: Não existe outra Issue para este problema?
    description: Por favor, antes de registrar uma nova solicitação procure nas Issues existentes pelo erro que você encontrou.
    options:
    - label: Eu fiz uma busca e não encontrei um Issue para o meu erro encontrado.
      required: true
- type: textarea
  attributes:
    label: Relato do problema encontrado
    description: Uma descrição concisa do problema encontrado.
  validations:
    required: false
- type: textarea
  attributes:
    label: Comportamento esperado
    description: Uma descrição concisa do comportamento esperado.
  validations:
    required: false
- type: textarea
  attributes:
    label: Passos para reproduzir o problema
    description: Descreva passo a passo como reproduzir o problema.
    placeholder: |
      1. Carregar dados históricos...
      2. Na aba configurações ajustar o valor da previsão de crescimento...
      3. Realizar previsão...
      4. Valor retornado não está considerando o valor definido no campo previsão de crescimento...
  validations:
    required: false
- type: textarea
  attributes:
    label: Algo mais a acrescentar?
    description: |
      Links? Referências? Alguma coisa a mais que possa auxiliar na reprodução do problema encontrado!
      
      Tip: É possível anexar imagens ou arquivos.
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    label: Qual o navegador web você utilizou para reproduzir o problema?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
